export function Footer() {
  return (
    <footer className="bg-foreground text-background py-12">
      <div className="container mx-auto px-6 md:px-8 lg:px-12 max-w-7xl">
        <div className="grid md:grid-cols-3 gap-8">
          <div>
            <h3 className="font-bold text-xl mb-4">Dhaka Tuition Market Report</h3>
            <p className="text-sm opacity-80">
              Comprehensive business intelligence for entrepreneurs entering the 
              BDT 1.5 billion Bangladeshi tuition market.
            </p>
          </div>
          <div>
            <h4 className="font-bold mb-4 uppercase text-sm tracking-wider">Quick Links</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="#market-overview" className="opacity-80 hover:opacity-100 transition-opacity cursor-pointer">
                  Market Overview
                </a>
              </li>
              <li>
                <a href="#competitive-landscape" className="opacity-80 hover:opacity-100 transition-opacity cursor-pointer">
                  Competitive Analysis
                </a>
              </li>
              <li>
                <a href="#recommendations" className="opacity-80 hover:opacity-100 transition-opacity cursor-pointer">
                  Strategic Recommendations
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold mb-4 uppercase text-sm tracking-wider">Key Markets</h4>
            <ul className="space-y-2 text-sm">
              <li className="opacity-80">Gulshan & Banani</li>
              <li className="opacity-80">Dhanmondi & Uttara</li>
              <li className="opacity-80">Bashundhara & Farmgate</li>
            </ul>
          </div>
        </div>
        <div className="border-t border-background/20 mt-10 pt-8">
          <p className="text-xs text-center opacity-60">
            Generated by Superagent.
          </p>
        </div>
      </div>
    </footer>
  );
}
